# Data generation

This section outlines how the simulated data is generated. First, a 'base' expression matrix is generated, with 1,000 variables (rows) and the number of samples equal to the sum of the four group sizes indicated by the user (by default, 5 per group/batch combination, giving a total sample size of 20). The base expression values are sampled independently from a normal distribution with mean 10 and standard deviation 2. The random seed used for the simulation can be changed by the user to generate a different matrix.

Next, the variables affected by the condition and/or batch effects (denoted here by $C$ and $B$, respectively) are sampled randomly among the full set of variables. The number of variables affected by each type of effect is determined by the user. 

For each variable in $C$, the base expression for the samples in condition c2 is either increased or decreased by the indicated condition effect size, determined by the user. The sign of the effect is randomly determined. Similarly, for each variable in $B$, the base expression for the samples in batch b2 is either increased or decreased by the indicated batch effect size. 

More formally, let $y_{ij}^0\in N(10,2)$ denote the base expression level of variable $i$ in sample $j$. Furthermore, let $S_{b2}$ denote the set of samples from batch $b2$, and similarly let $S_{c2}$ denote the set of samples from condition $c2$. Finally, let $C$ denote the set of variables affected by the condition, and $B$ the set of variables affected by the batch effect. Then, the simulated expression value for variable $i$ in sample $j$ is obtained by $$y_{ij}=y_{ij}^0 + (-1)^{\beta_C}\cdot\ell_C\cdot I(j\in S_{c2})\cdot I(i\in C) + (-1)^{\beta_B}\cdot\ell_B\cdot I(j\in S_{b2})\cdot I(i\in B).$$
Here, $\ell_C$ and $\ell_B$ denote the condition and batch effect sizes, respectively, $I$ denotes the indicator function, and $\beta_C$ and $\beta_B$ are random variables drawn from a Bernoulli(0.5) distribution. 

# Statistical testing

The data matrix generated as described above is next subjected to row-wise (independent) statistical tests. Depending on the analysis approach chosen by the user, a different model is fit. The returned p-values, however, always test the null hypothesis that there is no difference in the mean expression value between the two conditions. 

If the analysis approach is _Don't account for batch effect_, a linear model is fit for each row independently, with the condition as the sole predictor. With the _Include batch effect in model_ analysis approach, a linear model is fit with both the batch and condition annotations as predictors. 

With the _Remove batch effect in advance_ analysis approach, a linear model is first fit with the batch annotation as the sole predictor. Next, a new set of response values are generated by summing the residuals of this model and the estimated intercept. These new values are then used as the response in another linear model with the condition as the sole predictor. 

Finally, if the analysis approach is chosen to be _Remove batch effect in advance, accounting for condition_, first a linear model is fit with the condition as the only predictor. The residuals of this model are then used as the response variables in another linear model with the batch as the predictor. Finally, the fitted values of the first model and the residuals from the second are summed together and used as the response values in a linear model with the condition as the sole predictor. 

The model fitting returns a p-value for each variable. These are adjusted for multiple testing using the Benjamini-Hochberg method. 

